version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_sentiment
    ports:
      - "5432:5432"
